version: "3.7"

services:
  c3-monitoring-prometheus:
    image: prom/prometheus
    container_name: c3-monitoring-prometheus
    restart: unless-stopped
    # required to use user root
    user: root
    volumes:
      - ./volumes/prometheus/etc/prometheus:/etc/prometheus
      - ./volumes/prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    expose:
      - 9090      
    ports:
      - 9090:9090
    links:
      - c3-monitoring-cadvisor:c3-monitoring-cadvisor
      - c3-monitoring-alert-manager:c3-monitoring-alertmanager
    depends_on:
      - c3-monitoring-cadvisor

  c3-monitoring-grafana:
    image: grafana/grafana
    container_name: c3-monitoring-grafana
    # required to use user root
    user: root
    restart: unless-stopped
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    volumes:
      - ./volumes/grafana/etc/grafana/provisioning:/etc/grafana/provisioning
      - ./volumes/grafana/var/lib/grafana:/var/lib/grafana
    env_file:
      - ./volumes/grafana/etc/grafana/config.monitoring
    ports:
      - 9070:3000
    depends_on:
      - c3-monitoring-prometheus

  c3-monitoring-node-exporter:
    image: prom/node-exporter
    container_name: c3-monitoring-node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    expose:
      - 9100      
    restart: unless-stopped

  c3-monitoring-alert-manager:
    image: prom/alertmanager
    container_name: c3-monitoring-alert-manager
    restart: unless-stopped
    ports:
      - 9093:9093
    volumes:
      - ./volumes/alertmanager/etc/alertmanager:/etc/alertmanager/
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"

  c3-monitoring-cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: c3-monitoring-cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
    restart: unless-stopped

# optional one can use volumes
# volumes:
#   prometheus_data: {}
#   grafana_data: {}
